[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  from = "/logs"
  to = "/.netlify/functions/logs"
  status = 200

[[redirects]]
  from = "/logs/*"
  to = "/.netlify/functions/logs/:splat"
  status = 200
